＃　行列演算

In [4]:
import numpy as up

In [5]:
np.array([[1],[2],[3]])

NameError: name 'np' is not defined

In [6]:
import numpy

In [7]:
import numpy as np

In [9]:
x=np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [12]:
X=np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [14]:
Xt=X.T
print(Xt)

[[1 3]
 [2 4]]


In [17]:
X_inv=np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
XX_inv=np.dot(X,X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [19]:
x=np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [20]:
x.T

array([[1],
       [2],
       [3]])

In [26]:
X=np.array([
    [2,3,4],
    [1, 2, 3]
])

In [27]:
print(X)

[[2 3 4]
 [1 2 3]]


In [29]:
X.shape

(2, 3)

In [31]:
row,col=X.shape

In [32]:
row

2

In [33]:
col

3

In [34]:
for x in X:
    print(x)
    print('--')

[2 3 4]
--
[1 2 3]
--


In [36]:
X=np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])

print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [38]:
y=np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [44]:
XtX = np.dot(X.T, X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [47]:
XtX_inv=np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [49]:
Xty = np.dot(X.T ,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [51]:
w =np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


In [52]:
import sklearn

In [54]:
from sklearn.linear_model import LinearRegression

In [60]:
model = LinearRegression(fit_intercept=False)

In [61]:
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [62]:
model.coef_

array([[-0.14285714,  0.71428571,  0.57142857]])

In [63]:
model.intercept_

0.0

In [66]:
model.score(X,y)

0.6923076923076923

In [67]:
x = np.array([[1,2,3]])

In [69]:
y_pred = model.predict(x)
y_pred

array([[3.]])